package test;/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

        Review rev = new Restaurant("judy","its nice",7);
        Restaurant cast=(Restaurant) rev;
        cast.setName("hhhh");
//        Restaurant rev2 = new Restaurant("mariam","its nice",7);
//        cast.setName("lllll");
        cast.addReview(cast);
    }
}
