/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void readFile(String p){
        Path file= Paths.get(p);
        try(InputStream input = Files.newInputStream(file);
            BufferedReader reader = new BufferedReader(new InputStreamReader(input))) {
            String lines;
            StringBuilder editCode = new StringBuilder();
            for (int i=1;(lines=reader.readLine()) != null; i++){
                if ((!lines.endsWith(";")) && (!lines.endsWith("{")) && (!lines.endsWith("}")) && (!lines.contains("if")) && (!lines.contains("else"))) {
                    System.out.println("Line "+ i +": Missing semicolon.");
                    editCode.append(lines).append(";");
                }else{
                    editCode.append(lines).append(";\n");
                }
            }
        }catch (IOException err) {
            System.err.println(err);
        }
        }

    public static void main(String[] args) {
        readFile("C:\\Users\\LENOVO\\Documents\\lab3\\java-fundementals2\\linter\\app\\src\\main\\resources\\gates.js");
    }
}

