/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package referanceLab;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test public void testtoStringReview() {
        Review reviewTest = new Review("ok","mahmood",5);
        assertEquals("the Restaurant ok  voted 5  stars  mahmood","the Restaurant "+reviewTest.getAuthor() + "  voted " +reviewTest.getRevStars() +"  stars  " + reviewTest.getBody());
    }
    //"the Restaurant "+this.name + " has " +this.noOfStars +"  stars  " + this.priceCategory +" $"
    @Test public void testtoStringResturant() {
        Reastaurant resturantTest = new Reastaurant("mahmood","ok",4);
        resturantTest.setRestaurantName("shawrma");
        resturantTest.setNumStars(4);
        resturantTest.setPriceCatig(" $");
        assertEquals("the Restaurant shawrmahas 4stars $$", resturantTest.tostring());
    }
    @Test public void addReviewTest(){
        Review rev1 = new Reastaurant("judy","good",5);
        Reastaurant reviewCasting = (Reastaurant) rev1;
        reviewCasting.setRestaurantName("Zanjabeel");
//
        assertEquals ("{Zanjabeel=[good, judy, 0]}","{"+reviewCasting.getRestaurantName()+"=["+reviewCasting.getBody()+", "+reviewCasting.getAuthor()+", "+reviewCasting.getNumStars()+"]}");
    }
}
